library(reshape2)
library(data.table)
library(ggplot2)
library(DESeq2)
library(Vennerable)
library(fpc)
library(topGO)
library(org.Mm.eg.db)
library(GMD)
library(gplots)

source("preliminary.R")
source("clustering.R")
source("plot.R")
source("diff-expr.R")
source("go.R")
source("main-shortcuts.R")
source("posthoc-analysis.R")
