---
title: "PCA of light polysome fractions (8-10)"
author: "Vladimir Kiselev"
date: "19 February 2015"
output:
  pdf_document:
    number_sections: yes
    toc: no
---

```{r, echo=FALSE, include=FALSE, cache=TRUE}
library(gplots)
library(ggplot2)
```

```{r, echo=FALSE, cache=TRUE, fig.width=10, fig.height=10}
cor_heatmap <- function(count.matrix, name) {
        # plot a correlation matrix from a count matrix
        # calculate pearson's correlation coefficients
        cor.matrix <- cor(count.matrix, method = "pearson")
        # plot correlation matrix in a file with 'name'
        #   plot(1)
        heatmap.2(cor.matrix, Rowv = FALSE, Colv = FALSE, dendrogram = "none", col=bluered(9), breaks = 10, trace = "none", keysize = 1.0)
}
d <- readRDS("files/data-matrix-norm.rds")

cols <- colnames(d[,2:157])
j <- 4
for(i in 1:13){
  cols[grep(paste0("LUL1._e", i, "_"), cols)] <- paste0("L_", j)
  j <- j + 1
}
j <- 4
for(i in 14:26){
  cols[grep(paste0("LUL1._e", i, "_"), cols)] <- paste0("LE_", j)
  j <- j + 1
}
j <- 4
for(i in 27:39){
  cols[grep(paste0("LUL1._e", i, "_"), cols)] <- paste0("LEKU_", j)
  j <- j + 1
}
colnames(d)[2:157] <- cols
tmp <- as.matrix(d[,grepl("_([8-9]|10)", colnames(d), perl = TRUE)])
cor_heatmap(tmp[,order(colnames(tmp))], "polysome")
```

```{r, echo=FALSE, cache=TRUE, fig.width=4, fig.height=4}
res <- prcomp(d[,grepl("_([8-9]|10)", colnames(d), perl = TRUE)])
screeplot(res)
```
```{r, echo=FALSE, cache=TRUE, fig.width=4, fig.height=4}
data <- as.data.frame(res$rotation[,1:3])
data$cond <- rownames(data)
data$cond <- unlist(lapply(strsplit(data$cond, "\\."), function(x){return(x[1])}))
data$pf <- as.numeric(unlist(lapply(strsplit(data$cond, "_"), function(x){return(x[2])})))
data$cond <- unlist(lapply(strsplit(data$cond, "_"), function(x){return(x[1])}))
ggplot(data, aes(PC1,PC2)) +
geom_point(aes(shape = cond, color = as.factor(pf))) +
scale_size(range = c(3, 6)) +
theme_bw()
```
```{r, echo=FALSE, cache=TRUE, fig.width=4, fig.height=4}
ggplot(data, aes(PC2,PC3)) +
geom_point(aes(shape = cond, color = as.factor(pf))) +
scale_size(range = c(3, 6)) +
theme_bw()
```
```{r, echo=FALSE, cache=TRUE, fig.width=4, fig.height=4}
ggplot(data, aes(PC1,PC3)) +
geom_point(aes(shape = cond, color = as.factor(pf))) +
scale_size(range = c(3, 6)) +
theme_bw()
```
